// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc-test.proto

package pencode

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NumberedList struct {
	Numbers              []uint64 `protobuf:"varint,1,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumberedList) Reset()         { *m = NumberedList{} }
func (m *NumberedList) String() string { return proto.CompactTextString(m) }
func (*NumberedList) ProtoMessage()    {}
func (*NumberedList) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_test_e1ebcbb59bc3f11c, []int{0}
}
func (m *NumberedList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumberedList.Unmarshal(m, b)
}
func (m *NumberedList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumberedList.Marshal(b, m, deterministic)
}
func (dst *NumberedList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumberedList.Merge(dst, src)
}
func (m *NumberedList) XXX_Size() int {
	return xxx_messageInfo_NumberedList.Size(m)
}
func (m *NumberedList) XXX_DiscardUnknown() {
	xxx_messageInfo_NumberedList.DiscardUnknown(m)
}

var xxx_messageInfo_NumberedList proto.InternalMessageInfo

func (m *NumberedList) GetNumbers() []uint64 {
	if m != nil {
		return m.Numbers
	}
	return nil
}

func init() {
	proto.RegisterType((*NumberedList)(nil), "pencode.NumberedList")
}

func init() { proto.RegisterFile("grpc-test.proto", fileDescriptor_grpc_test_e1ebcbb59bc3f11c) }

var fileDescriptor_grpc_test_e1ebcbb59bc3f11c = []byte{
	// 88 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x2f, 0x2a, 0x48,
	0xd6, 0x2d, 0x49, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x48, 0xcd,
	0x4b, 0xce, 0x4f, 0x49, 0x55, 0xd2, 0xe0, 0xe2, 0xf1, 0x2b, 0xcd, 0x4d, 0x4a, 0x2d, 0x4a, 0x4d,
	0xf1, 0xc9, 0x2c, 0x2e, 0x11, 0x92, 0xe0, 0x62, 0xcf, 0x03, 0xf3, 0x8b, 0x25, 0x18, 0x15, 0x98,
	0x35, 0x58, 0x82, 0x60, 0xdc, 0x24, 0x36, 0xb0, 0x4e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x78, 0xcd, 0xea, 0x0a, 0x4c, 0x00, 0x00, 0x00,
}
